### ISSUE TITLE
HTML Entity in retrieved news text

### ISSUE THREAD

**Issue by Auenc** [techiaith/macsen-sgwrsfot#2]
Mae ddrwg gen i am defnyddio Saesneg ond dw i'n dal yn dysgu Cymraeg.

It's possible for a HTML entity/entities to be displayed as text when retrieving news. 

I have noticed `&#8217;` which appears to be an entity representing `'`.

![photo_2021-06-29_13-11-06 1](https://user-images.githubusercontent.com/14826315/123798760-70ff0580-d8df-11eb-9b58-2a38534b2f3e.png)

**Comment by Auenc** [comment]
If it is alright with you @DewiBrynJones would I be able to submit a pull request for the fix? I'd love to commit to the project and this is a nice starter. 

I'm just testing a fix using `HTMLParser` using the `unescape` function.

**Comment by DewiBrynJones** [comment]
A pull request would be excellent!
Diolch yn fawr!

**Comment by DewiBrynJones** [comment]
Helo

I merged your pull request and deployed to the server and it seems to be working :) . 

However there was one adjustment I had to make - https://github.com/techiaith/macsen-sgwrsfot/commit/a82d7f7b63646a0c2021a128109f9635df231089 - because of...

```
$ more cherrypy.error.log                                                       
[30/Jun/2021:07:14:12]  respond to - beth yw'r newyddion
[30/Jun/2021:07:14:14] HTTP Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 670, in respond
	response.body = self.handler()
 File "/usr/local/lib/python3.6/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
	self.body = self.oldhandler(*args, **kwargs)                                                                                                              File "/opt/skills-server/handlers.py", line 15, in callback_handler                                                                                           value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)                                                                                     File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__                                                                   return self.callable(*self.args, **self.kwargs)                                                                                                           File "/opt/skills-server/wsgi.py", line 100, in perform_skill                                                                                                 intent_name, output = self.brain.handle(text, latitude, longitude)
 File "/opt/skills-server/assistant/Brain.py", line 66, in handle
	skill_result=self.handle_intent(best_key, best_intent, latitude, longitude)
 File "/opt/skills-server/assistant/Brain.py", line 73, in handle_intent
	return self.skills[handler_key].handle(intent, latitude, longitude)
 File "/opt/skills-server/assistant/skills/newyddion/newyddion.py", line 46, in handle
    'title': html_parser.unescape(entry.get("title") + "."),
NameError: name 'html_parser' is not defined                              
```

we should have made it easier for you to test yourself. But it's a simple enough skill and easily resolvable.

Diolch eto!

**Comment by Auenc** [comment]
Dim problem! Dw i'n hapus i helpu pan dw i'n gallu!
